### ISSUE TITLE
translation_map parameter to to_field should permit array of values

### ISSUE THREAD

**Issue by barmintor** [projectblacklight/blacklight-marc#55]
when the translation_map parameter is an array of strings, each value should be resolved a s a translation map and merged. The source maps should be merged to give priority to the first value in the array.

```ruby
to_field "mapped", map_value(literal('k'),translation_map:["test_format_overrides","test_formats"])
```

**Comment by jrochkind** [comment]
I'm not sure where this `map_value` method is coming from (not traject I don't think?), but I will add this feature to road map for traject 3.0 out of the box as well.

**Comment by barmintor** [comment]
it's in `Blacklight::Marc::Indexer < Traject::Indexer`

**Comment by jrochkind** [comment]
I'm adding a translation map merge feature to traject 3.0, but I'm not sure how nicely traject 3.0 will play with the custom `Blacklight::Marc::Indexer` referenced here.  

If there's anyone available to talk about:

a) why the custom Blacklight::Marc::Indexer was created, particularly the `first_value` and `map_value` methods, which I don't totally understand their use or intention (or what value they are intended to add over the built-in traject API)

b) Any possible compatibility issues between traject 3.0 and traject as used in blacklight-marc, and if there's anything you'd like to be done in traject to make this go smoother. 

I would love to talk. 

I can potentially help suggest code you could put in the blacklight_marc Blacklight::Marc::Indexer too, to support this feature even in traject 2.0, I'll know more after I implement in traject 3.0 -- I'm focusing on traject 3.0 right now, and do not personally support or am familiar with blacklight_marc's custom traject stuff. Not sure who if anyone is supporting/maintaining blacklight_marc and it's custom traject overrides. 

The key thing to know is that Traject::TranslationMap (even in current release traject 2.0) has a #merge method that works much as you'd expect/want.

**Comment by jrochkind** [comment]
An implementation in blacklight_marc, that works with traject 2.0, _may_ be as simple as:

```ruby
  def map_value block, options={}
    if translation_map_arg  = options.delete(:translation_map)
      translation_map = Array(translation_map_arg).collect { | arg| Traject::TranslationMap.new(arg) }.reduce(:merge)
```
That last line is an edit to existing definition of method.

**Comment by barmintor** [comment]
Looking at the code and the context, the two possibilities I can imagine are:
1. It reflects the semantics of the previous java shell indexer dsl
2. There was a traject functions that didn't capture the use cases the indexer had (maybe the 2 argument or 3 argument cases weren't present).

**Comment by jrochkind** [comment]
Thanks @barmintor.

Looking at the [spec here](https://github.com/projectblacklight/blacklight-marc/blob/b7fde6c238dd5a1cd6a63aae17822ca18659efc7/spec/lib/traject_indexer_spec.rb), which includes a spec for `to_field "mapped", map_value(literal('k'),translation_map:"test_formats")` -- another possible reason is that in traject 2.x there is no built-in DSL-y way to apply a translation map to a literal. 

Not sure why you'd want to do that, but in traject 3.0 it will be possible like:

    to_field "mapped", literal('k'), translation_map("test_formats")

And that `translation_map` macro _will_ be able to take multiple translation map names (or even a hash), and merge them together. 

I'm not sure how traject 3.0 should be dealt with by the traject overrides here in blacklight-marc.  It may be there were use cases bl-marc had that traject didn't handle... one of the downsides of handling them with custom overrides like has been done here, is that when traject evolves to handle them (because it turns out more people have the use cases than just bl-marc)... you've got a bit of a "fork".  

Do you know if there's a current maintainer or "owner" of bl-marc, @barmintor ?  If not, perhaps you would like to be?  In the absence of that, now sure how we figure out how to handle traject 3.0. I'm happy to consult from the traject side to try to make sure traject makes things as easy as it can for bl-marc, but I don't have the time, energy, or context to decide what makes sense for bl-marc myself.

**Comment by barmintor** [comment]
the test translation map that `literal('k')` line feeds into is commented to apply to leader[6..7] - is it possible that there's a kind of pipeline use case that would require (or did require) handling an emitted literal?

**Comment by jrochkind** [comment]
Not that I can figure out. A `literal` is something not based on input. I'm not sure we're going to know the motivation for the 'map_value` method unless we figure out who added it and get them to tell us, if they remember. 

What it does is allow you to apply translation_map to arbitrary earlier extractions/transformations. Regardless of it's use-case motivation, traject 3.0 will let you do what it does, but using different API. So ideally someone responsible for blacklight-marc could be found to be engaged in discussing how we want to handle this with traject 3.0 coming out.
